apiVersion: apps/v1
kind: Deployment
metadata:
  name: Development Site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsitegit 
  template:
    metadata:
      labels:
        app: devsite
    spec:
      containers:
      - name: devsite-app
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID. 
        image: $LOCATION-docker.pkg.dev/$GCLOUD_PROJECT/hello-repo/helloworld-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"